tasks/opensource/setup-redhat.yml

Setup CentOS/RHEL repositories correctly

---

templates/http/api.conf.j2

Add conditional check

---

tasks/conf/push-config.yml
tasks/conf/setup-status.yml
tasks/conf/template-config.yml

Places templates in directories included from nginx.conf.j2

Fix template path issues

---

.travis.yml

Test plan: https://travis-ci.org/ienugr/ansible-role-nginx/builds/366015682

Update --sudo arguments to --become since --sudo has been deprecated

---

tasks/conf/push-config.yml

Replace *_upload_enable with *_push_enable

---

tasks/conf/push-config.yml

Use the path for nginx.conf instead of default.conf

Fix stat path

---

tasks/conf/push-config.yml
tasks/conf/template-config.yml

Use the backup parameter in the copy/template modules instead of using a convoluted backup system

Use copy/template backup parameter

---

.travis.yml
tests/dockerfiles/Dockerfile.centos-6
tests/dockerfiles/Dockerfile.centos-7
tests/dockerfiles/Dockerfile.debian-jessie
tests/dockerfiles/Dockerfile.debian-stretch
tests/dockerfiles/Dockerfile.ubuntu-trusty
tests/dockerfiles/Dockerfile.ubuntu-xenial
tests/files/http/default.conf
tests/files/nginx.conf
tests/inventory
tests/playbooks/nginx-opensource.yml
tests/playbooks/nginx-push.yml
tests/playbooks/nginx-template.yml
tests/playbooks/nginx-upload.yml

Implement support to test the role in multiple Linux distributions by deploying Docker containers within Travis

Test role across multiple distributions

---

tasks/keys/apt-key.yml

Hello @alessfg,
this fixes #38 by adding an updated key server configuration.
Reference: https://sks-keyservers.net/overview-of-pools.php
Thanks, Georgy

Updated key server to bypass firewalled environments. - Fixes #38

---

.travis.yml
README.md
defaults/main.yml
tasks/main.yml
tasks/opensource/install-oss.yml
tests/playbooks/nginx-unit.yml

Users can now choose to only install NGINX Unit

Add nginx_enable variable

---

tasks/main.yml
tasks/modules/install-geoip.yml
tasks/modules/install-modules.yml

Refactor and fix module installation

---

tasks/main.yml
tasks/prerequisites/install-prerequisites.yml
tasks/prerequisites/setup-debian.yml

Install Debian dependencies

---

tasks/main.yml

Only add repository key when nginx_repository is used.

---

tasks/modules/install-modules.yml
tasks/modules/install-perl.yml

Fix module install

---

README.md
defaults/main.yml
templates/http/default.conf.j2

Resolves https://github.com/nginxinc/ansible-role-nginx/issues/98
This PR gives an ability to configure basic authorization using dedicated configuration options.

Support for configuration of basic authorization

---

README.md
defaults/main.yml
templates/http/default.conf.j2
tests/playbooks/nginx-unit.yml

Add root parameter to server context

---

README.md
defaults/main.yml
tasks/conf/cleanup-config.yml
tasks/conf/template-config.yml
tasks/main.yml
tests/playbooks/nginx-stream-template.yml

Add parameter to cleanup existing NGINX configs

---

README.md
templates/http/default.conf.j2
tests/playbooks/nginx-http-template.yml

Add proxy_redirect parameter location blocks

Add proxy_redirect parameter for location blocks

---

defaults/main.yml
templates/http/default.conf.j2
templates/stream/default.conf.j2
tests/playbooks/nginx-stream-template.yml

Added config option to defaults under reverse_proxy locations and modified the default.conf.j2 to support this.
https://github.com/nginxinc/ansible-role-nginx/issues/115

Added support for try_files

---

tasks/amplify/install-amplify.yml
tasks/main.yml

Hit some issues while using this ansible role to setup the amplify agent on bionic
After applying the patches in this PR, appears to install without issue on my system

Amplify installation fixes

---

README.md
defaults/main.yml
templates/http/default.conf.j2

These changes add the `auth_request_set` directive to the nginx ansible role.

Add auth_request_set directive

---

README.md
defaults/main.yml
templates/http/default.conf.j2

Enables or disables session resumption through TLS session tickets.

Add ssl_session_tickets directive.

---

templates/http/default.conf.j2
templates/nginx.conf.j2

1. make variable nginx_main_template.http_global_autoindex optional
1. make location variables autoindex, html_file_location and html_file_name optional

Make some variables optional.

---

README.md
defaults/main.yml
templates/http/default.conf.j2

I found out that it is not possible to with current role implementation.
Here is a small patch that introduces an additional variable that can be defined for location.

Add ability to rewrite proxy pass locations

---

README.md
defaults/main.yml
templates/http/default.conf.j2

I noticed that the option to add allows and denies to a location was missing so I tried to fix it. If it is done in the incorrect order or the placement of the attributes could be better just comment and I will try to fix it :)

Added option to set allows and denies for locations

---

README.md
meta/main.yml
molecule/default/molecule.yml
molecule/stable_push/molecule.yml
molecule/template_module/molecule.yml
molecule/unit/molecule.yml
tasks/conf/template-config.yml
tasks/conf/upload-config.yml
tasks/keys/apt-key.yml

Add support for Debian Buster

---

README.md
defaults/main.yml
molecule/template_module/playbook.yml
templates/http/default.conf.j2
templates/nginx.conf.j2

Add templating options to logs

---

.travis.yml

This should reduce overall test times

Create Travis build matrix for molecule builds

---

defaults/main.yml
molecule/default/molecule.yml
molecule/default/playbook.yml
molecule/stable_push/molecule.yml
molecule/template_module/molecule.yml
molecule/unit/molecule.yml
tasks/opensource/install-oss.yml
tasks/plus/install-plus.yml

And remove outdated Debian Jessie Molecule tests

Add option to specify the version of NGINX to install

---

README.md
defaults/main.yml
templates/http/default.conf.j2

This suggestion adds on merge #161 which did not factor for the ability to use multiple times the "rewrite" directive which is useful and supported in nginx configuration.

Add support for multiple rewrite directives as per nginx conf

---

README.md
defaults/main.yml
tasks/conf/setup-status.yml
tasks/conf/template-config.yml
templates/http/api.conf.j2

Add variable to set location of NGINX status conf file

---

tasks/main.yml

(Disregard commit 42738d7 please)
Commit 64851a6:
Tags are very convenient to run selected tasks of the role. For example
```
ansible-playbook nginx.yml -t nginx_debug_output
```
will print the debug output only.

Tags added to main.yml

---

defaults/main.yml
templates/http/default.conf.j2

- Add proxy_send_timeout to variables
- Make zone parameter optional

Add proxy_sent_timeout and make upstream zones optional

---

README.md
defaults/main.yml
molecule/template/playbook.yml
tasks/conf/template-config.yml
templates/http/default.conf.j2

Make availability for adding multiple server blocks for Nginx HTTP config file.

Add multiple servers for reverse proxy template

---

README.md
defaults/main.yml
templates/nginx.conf.j2

Add tcp_nopush and tcp_nodelay vars to nginx.conf

Add tcp_nopush and tcp_nodelay vars

---

defaults/main/main.yml
tasks/opensource/install-oss-bsd.yml
tasks/opensource/install-oss-linux.yml
tasks/opensource/setup-alpine.yml
tasks/opensource/setup-debian.yml
tasks/opensource/setup-redhat.yml
tasks/opensource/setup-suse.yml
tasks/plus/install-plus-bsd.yml
tasks/plus/install-plus-linux.yml

Add option to use/update to the latest version of NGINX

---

defaults/main/template.yml
templates/http/default.conf.j2

Let users define the target https redirect variable

---

README.md
defaults/main/controller.yml
tasks/controller/install-controller.yml
tasks/controller/setup-controller-instance.yml
tasks/controller/setup-controller-repository.yml
tasks/controller/setup-debian.yml
tasks/controller/setup-redhat.yml
tasks/main.yml

Add the option to pull the NGINX Controller agent install script from the NGINX Controller instance

Add new method to install the NGINX Controller agent

---

tasks/opensource/setup-debian.yml

Describe the use case and detail of the change. If this PR addresses an issue on GitHub, make sure to include a link to that issue here in this description (not in the title of the PR).

apt update (after installation from the nginx repo) gives an error #210

---

tasks/amplify/setup-debian.yml
tasks/controller/setup-controller-repository.yml
tasks/plus/setup-debian.yml
tasks/unit/setup-debian.yml

Describe the use case and detail of the change. If this PR addresses an issue on GitHub, make sure to include a link to that issue here in this description (not in the title of the PR).

Only add Debian repositories when installing role in amd64 archs

---

.travis.yml

Always pulling the latest version may lead to some issues. Versions should only be updated after successfully testing the latest release.

Add Ansible and Molecule versions to Travis

---

tasks/controller/setup-controller-repository.yml

Add OS family check to the NGINX Controller Agent repository setup. Resolves #223.

Add OS family check

---

defaults/main/template.yml
molecule/common/playbook_template.yml
templates/http/default.conf.j2
templates/nginx.conf.j2

Implement ngx_http_sub_module (https://github.com/nginxinc/ansible-role-nginx/pull/215)
-   [ ] I have added Molecule tests that prove my fix is effective or that my feature works

Add implementation of ngx_http_sub_module config

---

defaults/main/main.yml
tasks/modules/install-geoip.yml
tasks/modules/install-image-filter.yml
tasks/modules/install-njs.yml
tasks/modules/install-perl.yml
tasks/modules/install-rtmp.yml
tasks/modules/install-waf.yml
tasks/modules/install-xslt.yml

This is to add logic for nginx_version to be honored in module installs.
https://github.com/nginxinc/ansible-role-nginx/issues/239
-   [X] I have read the [CONTRIBUTING](https://github.com/nginxinc/ansible-role-nginx/blob/master/CONTRIBUTING.md) document
-   [X] I have added Molecule tests that prove my fix is effective or that my feature works
-   [X] I have checked that all unit tests pass after adding my changes
-   [X] If required, I have updated necessary documentation (`defaults/main/` and `README.md`)

Issue239 - fix nginx_version in module install

---

tasks/conf/upload-config.yml

I'm launching role with --diff. That option logging what changed.

Restrict logging certificate content in diff mode

---

.travis.yml
README.md
defaults/main/main.yml
meta/main.yml
molecule/common/Dockerfile.j2
molecule/common/playbook_default.yml
molecule/common/playbook_default_verifier.yml
molecule/default/molecule.yml
molecule/module/molecule.yml
molecule/source/molecule.yml
molecule/stable_push/molecule.yml
molecule/template/molecule.yml
molecule/unit/molecule.yml
tasks/opensource/setup-source.yml

Add Ubuntu Focal as a supported platform

Add support for Ubuntu Focal

---

molecule/common/playbook_default.yml
molecule/common/playbook_template.yml
templates/http/default.conf.j2

Add support for unix upstreams. Resolves #232.

Add support for unix upstreams

---

defaults/main/template.yml
molecule/common/playbook_template.yml
tasks/conf/setup-status.yml
tasks/conf/template-config.yml
templates/http/api.conf.j2

Add `access_log` to status and API configuration files. Resolves #225.

Add `access_log` to status and API configuration files

---

defaults/main/template.yml
molecule/common/playbook_template.yml
templates/nginx.conf.j2

Add PID templating option. Resolves #243.

Add PID templating option

---

tasks/modules/install-geoip.yml
tasks/modules/install-njs.yml
tasks/opensource/setup-debian.yml
tasks/plus/setup-license.yml
tasks/unit/install-modules.yml
tasks/unit/setup-debian.yml

`loop` is now the recommended way to loop through lists instead of `with_items`

Replace `with_items` with `loop`

---

CHANGELOG.md
defaults/main/linux.yml
defaults/main/main.yml
molecule/common/playbook_default.yml
tasks/main.yml

Add separate variables for installing and configuring NGINX.

Add separate variables for installing and configuring NGINX

---

CHANGELOG.md
defaults/main/template.yml
molecule/common/playbooks/template_converge.yml
templates/stream/default.conf.j2

Improve support for listen and ssl directives in stream contexts. Resolves #286. 

Improve support for listen and ssl directives in stream contexts

---

molecule/common/playbooks/source_converge.yml
tasks/opensource/setup-source.yml
tasks/prerequisites/setup-debian.yml

Cleanup source install and remove shell module tasks.

Cleanup source install and remove shell module tasks

---

defaults/main/main.yml
molecule/common/playbooks/module_converge.yml
tasks/conf/cleanup-config.yml

Add option to remove a specific list of files

Add option to remove a specific list of files

---

defaults/main/amplify.yml
defaults/main/template.yml
tasks/amplify/setup-debian.yml
tasks/keys/setup-keys.yml
tasks/modules/install-geoip.yml
tasks/modules/install-modules.yml
tasks/opensource/install-oss-bsd.yml
tasks/opensource/install-oss-linux.yml
tasks/opensource/setup-source.yml
tasks/prerequisites/setup-freebsd.yml
tasks/prerequisites/setup-selinux.yml
tasks/prerequisites/setup-systemd.yml

Add experimental support for Ubuntu focal and work on some minor formatting improvements. Resolves #248. 

Add experimental support for Ubuntu focal

---

defaults/main/template.yml
molecule/common/playbooks/template_converge.yml
templates/nginx.conf.j2

Add `nginx_main_template.http_settings.default_type` templating option.

Add `default_type` templating option

---

.travis.yml
molecule/default/molecule.yml
molecule/default_alpine/molecule.yml
molecule/default_centos/molecule.yml
molecule/module/molecule.yml
molecule/module_alpine/molecule.yml
molecule/module_centos/molecule.yml
molecule/source/molecule.yml
molecule/source_alpine/molecule.yml
molecule/source_centos/molecule.yml
molecule/stable_push/molecule.yml
molecule/stable_push_alpine/molecule.yml
molecule/stable_push_centos/molecule.yml
molecule/template/molecule.yml
molecule/template_alpine/molecule.yml
molecule/template_centos/molecule.yml
molecule/unit/molecule.yml
molecule/unit_alpine/molecule.yml
molecule/unit_centos/molecule.yml

Update Ansible Lint to `4.3.3`

Update Ansible Lint to 4.3.3

---

meta/main.yml

Update Ansible Galaxy metadata

Update Ansible Galaxy metadata

---

.travis.yml
CHANGELOG.md

Update Ansible to `2.9.13` and Ansible Lint to `4.3.4`

Update Ansible to 2.9.13

---

CHANGELOG.md
README.md
molecule/common/playbooks/default_converge.yml
molecule/common/playbooks/template_converge.yml
molecule/default_alpine/molecule.yml
molecule/module_alpine/molecule.yml
molecule/source_alpine/molecule.yml
molecule/stable_push_alpine/molecule.yml
molecule/template_alpine/molecule.yml
molecule/unit_alpine/molecule.yml
tasks/opensource/setup-source.yml

Add support for Alpine `3.12` and remove support for Alpine `3.8`

Add support for Alpine 3.12

---

.travis.yml
README.md
molecule/common/playbooks/plus_converge.yml
molecule/common/playbooks/plus_verify.yml
molecule/plus/molecule.yml
molecule/plus_alpine/molecule.yml
molecule/plus_centos/molecule.yml

Add NGINX Plus tests. For the time being, these can only be tested locally.

Add NGINX Plus tests

---

CHANGELOG.md
handlers/main.yml
tasks/config/modify-systemd.yml
tasks/config/template-config.yml
tasks/config/upload-config.yml
tasks/opensource/install-alpine.yml
tasks/opensource/install-bsd.yml
tasks/opensource/install-debian.yml
tasks/opensource/install-oss.yml
tasks/opensource/install-redhat.yml
tasks/opensource/install-source.yml
tasks/opensource/install-suse.yml
tasks/plus/install-alpine.yml
tasks/plus/install-debian.yml
tasks/plus/install-freebsd.yml
tasks/plus/install-redhat.yml
tasks/plus/install-suse.yml
tasks/plus/setup-license.yml

Added handlers to check for NGINX syntax validity and fail if any errors are detected.

Refactor handlers

---

tasks/amplify/install-amplify.yml
tasks/amplify/setup-debian.yml
tasks/config/cleanup-config.yml
tasks/opensource/install-source.yml
tasks/plus/install-plus.yml
vars/main.yml

Remove scalars where I don't need em

---

CHANGELOG.md
defaults/main/main.yml
handlers/main.yml
tasks/config/debug-output.yml
tasks/config/modify-systemd.yml
tasks/config/setup-logrotate.yml
tasks/keys/setup-keys.yml
tasks/opensource/install-oss.yml
tasks/plus/install-plus.yml
tasks/plus/setup-license.yml
tasks/prerequisites/prerequisites.yml
tasks/unit/install-modules.yml
tasks/unit/install-unit.yml

Improve the error formatting when there's a syntax error and remove the debug tasks messages. Need to look into a better process to improve debugging capabilities.

Improve the error formatting when there's a syntax error

---

.travis.yml
CHANGELOG.md

Update Ansible Lint to `4.3.5`

Update Ansible Lint

---

CHANGELOG.md
tasks/prerequisites/prerequisites.yml
tasks/prerequisites/setup-selinux.yml

Some of the facts used to detect the SELinux mode are not correctly formatted, as detailed in https://github.com/nginxinc/ansible-role-nginx-config/pull/30. (Separate repo with the same SELinux implementation). This PR aims to fix that issue in this repo too.

Fix SELinux facts

---

CHANGELOG.md
handlers/main.yml
tasks/config/debug-output.yml
tasks/opensource/install-alpine.yml
tasks/opensource/install-bsd.yml
tasks/opensource/install-debian.yml
tasks/opensource/install-redhat.yml
tasks/opensource/install-source.yml
tasks/opensource/install-suse.yml
tasks/plus/install-alpine.yml
tasks/plus/install-debian.yml
tasks/plus/install-redhat.yml
tasks/plus/install-suse.yml

Some tasks would incorrectly fail when running the role in check mode. Originally reported in 
https://github.com/nginxinc/ansible-role-nginx-config/issues/32

Fix errors when using Ansible's check mode

---

CHANGELOG.md

Prepare 0.17.3 release

---

CHANGELOG.md
tasks/keys/setup-keys.yml
tasks/opensource/install-alpine.yml
tasks/opensource/install-debian.yml
tasks/opensource/install-oss.yml
tasks/opensource/install-redhat.yml
tasks/opensource/install-suse.yml
tasks/plus/install-suse.yml
vars/main.yml

Switch NGINX keysites and OSS default repository data from a dictionary to individual variables to prevent potential issues arisen from Jinja2 dictionary run-time evaluations.

Switch dictionaries to individual variables

---

.gitignore
.travis.yml
CHANGELOG.md
README.md
meta/main.yml
molecule/default_alpine/molecule.yml
molecule/default_centos/molecule.yml
molecule/module_alpine/molecule.yml
molecule/module_centos/molecule.yml
molecule/plus_alpine/molecule.yml
molecule/plus_centos/molecule.yml
molecule/source_alpine/molecule.yml
molecule/source_centos/molecule.yml
molecule/stable_push_alpine/molecule.yml
molecule/stable_push_centos/molecule.yml
molecule/template_alpine/molecule.yml
molecule/template_centos/molecule.yml

*   Update Molecule to `3.2.0` and Docker Python SDK to `4.4.0`.
*   Add Alpine `3.12` to supported platforms for NGINX Plus.
*   Remove Alpine `3.9` and CentOS/RHEL `6` from supported platforms due to EOL.

Update packages and list of supported platforms

---

.github/workflows/molecule.yml
.github/workflows/requirements/requirements_ansible.yml
CHANGELOG.md
README.md
tasks/opensource/install-source.yml

Update the Ansible `community.general` collection to `2.5.1` and `community.docker` collection to `1.5.0`. And while at it, remove the temporary GitHub actions step to uninstall the Ansible community distribution (it's no longer an Ansible Lint dependency).

Update Ansible collections

---

.github/release-drafter.yml
.github/workflows/release-drafter.yml
CHANGELOG.md
README.md

First pass at a simple Release Drafter implementation.

Implement Release Drafter

---

.github/release-drafter.yml
.github/workflows/release-drafter.yml

Minor Release Drafter tweaks

---

.github/release-drafter.yml
.github/workflows/release-drafter.yml

Add `skip-changelog` label to the exclude labels category, and reincorporate the on push action for the Release Drafter GitHub action.

Further Release Drafter tweaks

---

.github/workflows/galaxy.yml
.github/workflows/molecule.yml

Specify GitHub actions checkout release.

Specify GitHub actions checkout release

---

.github/workflows/galaxy.yml
.github/workflows/molecule.yml
.github/workflows/release-drafter.yml
.yamllint
CHANGELOG.md
handlers/main.yml
molecule/default/verify.yml
molecule/module/verify.yml
molecule/plus/prepare.yml
molecule/plus/verify.yml
molecule/source/verify.yml
tasks/amplify/install-amplify.yml
tasks/amplify/setup-debian.yml
tasks/amplify/setup-redhat.yml
tasks/config/debug-output.yml
tasks/keys/setup-keys.yml
tasks/main.yml
tasks/opensource/install-alpine.yml
tasks/opensource/install-bsd.yml
tasks/opensource/install-debian.yml
tasks/opensource/install-redhat.yml
tasks/opensource/install-source.yml
tasks/opensource/install-suse.yml
tasks/plus/install-debian.yml
tasks/plus/install-freebsd.yml
tasks/plus/install-redhat.yml
tasks/plus/install-suse.yml
tasks/plus/setup-license.yml
tasks/prerequisites/install-dependencies.yml
tasks/prerequisites/setup-selinux.yml

Replace "yes"/"no" boolean values with "true"/"false" to comply with YAML spec `1.2`.

Replace "yes"/"no" boolean values with "true"/"false"

---

vars/main.yml

Select amd64 or arm64 by its architecture of machine on Debian, Ubuntu systems

switch arm64 repository if running on arm64 Debian/Ubuntu

---

CHANGELOG.md
README.md
meta/main.yml
molecule/common/Dockerfile.j2
molecule/default/converge.yml
molecule/default/molecule.yml
molecule/module/molecule.yml
molecule/plus/converge.yml
molecule/plus/molecule.yml
molecule/source/molecule.yml
tasks/opensource/install-redhat.yml
vars/main.yml

FEATURES:
Support installing NGINX OSS in Amazon Linux.
ENHANCEMENTS:
*   Update the README and Ansible metadata matrix of supported distributions.
*   Update the Molecule tests to include the newly supported distributions and remove distributions that are no longer supported.

Add support for installing NGINX OSS in Amazon Linux

---

tasks/opensource/install-source.yml

Just changing the PCRE URL because the one present on the code is not available anymore. 

Update PCRE ftp url

---

CHANGELOG.md
molecule/common/Dockerfile.j2
molecule/default/converge.yml
molecule/default/molecule.yml
molecule/downgrade/converge.yml
molecule/downgrade/molecule.yml
molecule/downgrade_plus/converge.yml
molecule/downgrade_plus/molecule.yml
molecule/module/molecule.yml
molecule/plus/molecule.yml
molecule/source/molecule.yml
molecule/uninstall/molecule.yml
molecule/uninstall_plus/molecule.yml
molecule/upgrade/molecule.yml
molecule/upgrade/prepare.yml
molecule/upgrade_plus/molecule.yml
molecule/upgrade_plus/prepare.yml
tasks/config/setup-logrotate.yml
tasks/opensource/install-source.yml
tasks/opensource/install-suse.yml
tasks/plus/install-suse.yml
tasks/plus/setup-license.yml
vars/main.yml

Add SLES 15 to all Molecule tests.

Add SLES tests

---

.github/release-drafter.yml
.github/workflows/requirements/requirements_ansible.yml
.github/workflows/requirements/requirements_molecule.txt
CHANGELOG.md
README.md
molecule/downgrade-plus/molecule.yml
molecule/plus/molecule.yml
molecule/uninstall-plus/molecule.yml
molecule/upgrade-plus/molecule.yml
tasks/opensource/install-bsd.yml

- Replace `molecule[docker]` with `molecule` and `molecule-plugins[docker]`.
- Add pre-releases to Release Drafter.

Explicitly set `molecule-plugins` and `ansible-compat` releases

---

molecule/default/verify.yml
tasks/plus/setup-license.yml

Due to the limited testing capabilities re NGINX Plus on external PRs, a bug was accidentally introduced in #620.

Fix bug introduced in #620

---

CHANGELOG.md
defaults/main/logrotate.yml
molecule/default/converge.yml
templates/logrotate/nginx.j2

Add option to use strings when configuring logrotate

---

CHANGELOG.md
README.md
molecule/agent/cleanup.yml
molecule/agent/molecule.yml
molecule/default/molecule.yml
molecule/distribution/molecule.yml
molecule/downgrade/molecule.yml
molecule/source-version/molecule.yml
molecule/source/molecule.yml
molecule/stable/molecule.yml
molecule/uninstall/molecule.yml
molecule/upgrade/molecule.yml
molecule/version/molecule.yml
vars/main.yml

chore!: Remove support for Alpine Linux 3.16

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md
CHANGELOG.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
SECURITY.md
SUPPORT.md

Update community docs per the latest [NGINX template repository](https://github.com/nginxinc/template-repository) guidelines.

docs: Update community docs

---

CHANGELOG.md
README.md
molecule/agent/molecule.yml
tasks/agent/install-agent.yml
tasks/agent/setup-alpine.yml
tasks/agent/setup-debian.yml
tasks/agent/setup-redhat.yml
tasks/agent/setup-suse.yml

feat: Add support for installing NGINX Agent on Ubuntu noble

---

.github/workflows/requirements/requirements_collections.yml
CHANGELOG.md
README.md

Bump the Ansible `community.general` collection to `9.2.0`, `community.crypto` collection to `2.21.1` and `community.docker` collection to `3.11.0`.

feat: Bump Ansible collections

---

handlers/main.yml

Minor PR with minor style changes.

style: Tweak Ansible handlers

---

CHANGELOG.md
tasks/validate/validate.yml

Add validation tasks to check the Ansible version, the Jinja2 version, and whether the required Ansible collections for this role are installed.

feat: Add Ansible/Jinja2/Collections validation

---

.github/workflows/ossf-scorecard.yml
CHANGELOG.md

ci: Implement OSSF Scorecard

---

CHANGELOG.md
molecule/agent/molecule.yml
molecule/amplify/molecule.yml
molecule/default/molecule.yml
molecule/distribution/molecule.yml
molecule/downgrade-plus/molecule.yml
molecule/downgrade/molecule.yml
molecule/plus/molecule.yml
molecule/source-version/molecule.yml
molecule/source/molecule.yml
molecule/stable/molecule.yml
molecule/uninstall-plus/molecule.yml
molecule/uninstall/molecule.yml
molecule/upgrade-plus/molecule.yml
molecule/upgrade/molecule.yml
molecule/version/molecule.yml

test: Update RHEL UBI images to UBI 8.10 and UBI 9.4

---

templates/logrotate/nginx.j2
templates/selinux/nginx-plus-module.te.j2
templates/services/nginx.service.override.conf.j2

Add an "Ansible managed" comment to the various templated configs deployed by the role.

chore: Add `ansible_managed` comment to templated configs

---

.github/workflows/milestone_pr.yml

Fix the `milestone_pr.yml` workflow by replacing the project link.

fix: The migrated project has changed number

---

README.md

docs: Fix survey link
