nginx/ansible-role-nginx

- tasks/modules/install-waf.yml
The main.yml task already checks for the waf variable - adding an additional check in install-waf.yml is redundant
> Remove redundant check

- tasks/plus/setup-debian.yml
- tasks/plus/setup-freebsd.yml
- tasks/plus/setup-redhat.yml
The get_url module has python 2.7 dependencies. This causes errors on distros that have strict python 2.6 dependencies. Replacing the get_url module with a hardcoded code block using the blockinfile module circumvents these errors.
> Replace get_url module

- tasks/opensource/install-oss.yml
- tasks/opensource/setup-freebsd.yml
Use FreeBSD ports instead of pkgng to fetch the latest version of NGINX Open Source
> Implement FreeBSD support for NGINX Open Source

- handlers/main.yml
- "enabled:yes" directive was added to Start NGINX handler
https://github.com/nginxinc/ansible-role-nginx/issues/54
> [Issue#54] Start NGINX handler was corrected

- tasks/prerequisites/setup-debian.yml
When install nginx in Ubuntu-18.04, a warning will happen 
this PR will fix the warning.
> fix `[WARNING]: Ignoring invalid attribute: Name`

- defaults/main.yml
- templates/http/default.conf.j2
Enable setting passive health checks by vars (last line)
```nginx_http_template_enable: false
nginx_http_template:
default:
template_file: http/default.conf.j2
conf_file_name: default.conf
conf_file_location: /etc/nginx/conf.d/
port: 8081
server_name: localhost
error_page: /usr/share/nginx/html
upstreams:
upstream1:
name: backend
lb_method: least_conn
zone_name: backend
zone_size: 64k
sticky_cookie: false
servers:
server1:
address: localhost
port: 8081
weight: 1
health_check: max_fails=3 fail_timeout=5s
> Allow setting a passive health checks

- README.md
- defaults/main.yml
- templates/http/default.conf.j2
- templates/nginx.conf.j2
- tests/playbooks/nginx-template.yml
Added variables and jinja conditions to enable autoindex in http, server and location namespaces according to issue #74
> Enable autoindex in http, server and location namespaces

- templates/http/default.conf.j2
- templates/nginx.conf.j2
- templates/stream/stream.conf.j2
- templates/www/index.html.j2
Best practice is that all templates handled by Ansible should have {{ ansible_managed }} at the top so everyone knows local changes may be overwritten.
> Add ansible_managed to templates

- README.md
- defaults/main.yml
- templates/http/default.conf.j2
A common function is to have a port server listening to http and redirect to https.
This adds a simple common redirect option. I don't know if you have more detailed plans for this option.
> Add support for enabling an http to https redirects

- README.md
- defaults/main.yml
- templates/http/default.conf.j2
https://www.nginx.com/blog/websocket-nginx
I couldn't really decide what was a good position of the websocket key so I just put it somewhere. I will ofcourse move it or change name of it based on the comments on this PR.
> Websocket support enabled for reverse proxy locations.

- templates/http/default.conf.j2
- templates/nginx.conf.j2
- templates/stream/default.conf.j2
This'll allow you to use a multi-line ansible_managed message. This chain is not compatible with ansible 1.x, but that's already broken with the use of 'become' instead of 'sudo' likely among other things.
> Support multi-line ansible_managed messages

- README.md
- defaults/main.yml
- handlers/main.yml
Some sites may prefer to start nginx manually, or via a different method from the `service` command.
> Make starting the nginx service optional.

- README.md
I may or may not have gotten bit by this and I'm blaming documentation even though the correct variable name is right there.
> Reference the correct variable name in comment

- README.md
- defaults/main.yml
- templates/http/default.conf.j2
Was having an issue to make my entire site to have password protection as the template only provides 'location' level protection.
According to the official docs, we can enable http authentication on 'server' level: https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/
> Allow auth basic to be added to global (server)

- README.md
- defaults/main.yml
- handlers/main.yml
- meta/main.yml
- tasks/keys/apk-key.yml
- tasks/main.yml
- tasks/opensource/setup-alpine.yml
- tasks/opensource/setup-suse.yml
- tasks/plus/install-plus.yml
- tasks/plus/setup-alpine.yml
- tasks/plus/setup-license.yml
- tasks/plus/setup-redhat.yml
- tasks/plus/setup-suse.yml
* Also address Ansible 2.8 'bare variable' deprecation warnings
> Add support to the role for RHEL 8 and Alpine Linux

- templates/http/default.conf.j2
If catch-all ("`_`") is used as `server_name`and `https_redirect` is `true`, `_` will be replaced with `$host` for `return 301`.
Ref: #137
> Catch-all ("_") check for https redirect

- README.md
- defaults/main.yml
- templates/http/default.conf.j2
Add support for adding headers either in the server or in the location (either web_server or revers_proxy) block.
> Add `add_header` support for either `server` and `location` block

- README.md
- defaults/main.yml
- templates/http/default.conf.j2
Add `ssl_trusted_certificate`, `ssl_stapling`, `ssl_stapling_verify` to configure OCSP stapling.
> Add directives to use OCSP Stapling

- README.md
- defaults/main.yml
- templates/http/default.conf.j2
Specifies that server ciphers should be preferred over client ciphers when using the SSLv3 and TLS protocols.
> Add directive ssl_prefer_server_ciphers

- README.md
- defaults/main.yml
- templates/http/default.conf.j2
Add websockets configuration back to http template file.
I also implemented the changes from #111 and made `proxy_http_version` configurable.
By default (when the variable is not defined) it is not added to the configuration.
Ref: #139
> Add websockets configuration back to http template

- README.md
- defaults/main.yml
- templates/http/default.conf.j2
- tests/playbooks/nginx-http-template.yml
Enables or disables buffering of responses from the proxied server.
When buffering is enabled, nginx receives a response from the proxied server as soon as possible, saving it into the buffers set by the proxy_buffer_size and proxy_buffers directives. If the whole response does not fit into memory, a part of it can be saved to a temporary file on the disk. Writing to temporary files is controlled by the proxy_max_temp_file_size and proxy_temp_file_write_size directives.
When buffering is disabled, the response is passed to a client synchronously, immediately as it is received. nginx will not try to read the whole response from the proxied server. The maximum size of the data that nginx can receive from the server at a time is set by the proxy_buffer_size directive.
> Add proxy_buffering directive to reverse proxy block

- README.md
- defaults/main.yml
- templates/http/default.conf.j2
- tests/playbooks/nginx-http-template.yml
By default, nginx does not pass the header fields “Date”, “Server”, “X-Pad”, and “X-Accel-...” from the response of a proxied server to a client. The proxy_hide_header directive sets additional fields that will not be passed. If, on the contrary, the passing of fields needs to be permitted, the proxy_pass_header directive can be used.
Usage:
```
proxy_hide_headers:
- X-Powered-By
- X-You-Shall-Not-Pass
- [...]
```
> Add proxy_hide-header directive

- README.md
- defaults/main.yml
- templates/http/default.conf.j2
- tests/playbooks/nginx-http-template.yml
Sets a text that should be changed in the path attribute of the “Set-Cookie” header fields of a proxied server response. Suppose a proxied server returned the “Set-Cookie” header field with the attribute “path=/two/some/uri/”. The directive
> proxy_cookie_path /two/ /;  
will rewrite this attribute to “path=/some/uri/”.
The path and replacement strings can contain variables:  
> proxy_cookie_path $uri /some$uri;
Usage:  
```yaml
proxy_cookie_path:
path: /web/
replacement: /
```
> Proxy cookie path

- README.md
- defaults/main.yml
- templates/http/default.conf.j2
I've implemented support for the 'client_max_body_size' parameter in the templated configuration, both at the `server` and `location` levels (missing as per  #155).
> Support 'client_max_body_size' (server, location)

- README.md
- defaults/main.yml
- templates/http/default.conf.j2
- templates/stream/default.conf.j2
Our original necessity is the same as #133, but we'd rather implement it through an `include` directive and a whitelist file.
Additionally, it shores up missing support for other directives that might not have yet been implemented.
> Support for 'include' directive in http templating

- README.md
- defaults/main.yml
- templates/http/default.conf.j2
- tests/playbooks/nginx-http-template.yml
This pull request adds the possibility to open an IPv6 socket and make the listen options configurable
(besides 'ssl' for ssl enabled servers and 'ipv6only=on' for IPv6 listeners).
**This change will break the current behavior how ports are defined!**
Old way:  
```
port: 8080
```
New way:  
```
listen:
port: 8080
opts: # Listen opts like http2 which will be added (ssl is automatically added if you specify 'ssl:').
- default_server
ipv4: true
ipv6: true
```
Ref:
- #146 
- #85
> Add IPv6 listener support; Make listen options configurable

- README.md
- defaults/main.yml
- templates/nginx.conf.j2
Since `worker_rlimit_nofile` has no default value ([ref](http://nginx.org/en/docs/ngx_core_module.html#worker_rlimit_nofile)), I used the dummy value `undefined` and use the setting only if it's different.
> Add setting worker_rlimit_nofile

- README.md
- defaults/main.yml
- molecule/template/playbook.yml
- templates/http/default.conf.j2
I noticed that the default template did not have support for `proxy_cache_valid`. In this PR, I have:
- Updated the default template so it accepts and renders proxy_valid_cache
- Updated the README
- Updated the molecule playbook and run the molecule test suite to ensure it passes.
Please let me know if you have any questions.
> Added proxy_cache_valid support

- templates/nginx.conf.j2
There were a bug for `tcp_nopush` and `tcp_nodelay` that were getting from `nginx_main_template`
> Fixed bug on tcp_nopush and tcp_nodelay for nginx.conf.j2

- templates/http/default.conf.j2
The default load balancing method in Nginx is `round-robin`, this is achieved by not defining `lb_method`.
In this case, if people want `least-connected` or `ip-hash`, they can define `lb_method` and it will work as before.
> Don't enforce the use of lb_method in upstream.

- README.md
- meta/main.yml
* Meta min_ansible_version: 2.7; last maintained version
* README updated; Role developed with maintained versions
Proposed Ansible update plan (As discussed in #193 )
- it should at least be updated to the least supported version at the moment
- it'd be good to follow the official Ansible version support guidelines
https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html
- make sure the role works with the latest three Ansible releases
>     Configure min_ansible_version

- defaults/main/main.yml
- tasks/main.yml
- tasks/plus/delete-license.yml
- tasks/plus/install-plus-bsd.yml
- tasks/plus/install-plus-linux.yml
- tasks/plus/setup-alpine.yml
- tasks/plus/setup-bsd.yml
- tasks/plus/setup-debian.yml
- tasks/plus/setup-license.yml
- tasks/plus/setup-redhat.yml
- tasks/plus/setup-suse.yml
This fixes a bug when only the license is deleted, making system updates fail since the NGINX Plus repository is still within the repositories list yet there is no license to authenticate to the repository
> Delete NGINX Plus repository when license is deleted

- README.md
- defaults/main/template.yml
- templates/http/default.conf.j2
Make ssl optional for listeners to not force ssl on ports like 80
-   [ ] I have added Molecule tests that prove my fix is effective or that my feature works
> Make ssl optional for listeners

- .travis.yml
- meta/main.yml
An issue was introduced in 2.8.8 and 2.9.3 that breaks the `disablerepo` parameter in the `yum` module. Ansible 2.9.4 fixes this issue, but for the time being the fix has not been back ported to 2.8. Ansible 2.7 should still work, but I'm making the decision to set 2.9 as the minimum version given the circumstances.
Resolves #219 
> Update minimum Ansible version

- README.md
- defaults/main/logrotate.yml
- molecule/common/playbook_template.yml
- tasks/conf/logrotate.yml
- tasks/main.yml
- templates/logrotate/nginx.j2
> Add custom logrotate config

- defaults/main/template.yml
- templates/http/default.conf.j2
Added only the possibility to edit ssl_buffer_size, ssl_ecdh_curve when using default.conf template.
> Add ssl_ecdh_curve and ssl_buffer_size directives

- templates/http/default.conf.j2
Hello, thank you for the great work.
For reverse proxy the two variable :
- websocket
- proxy_http_version
Are not handle by the default http template if the variable:
- proxy_set_header
is not set
So to make them work if you don't have any other header to set, you have to declare an empty **proxy_set_header** variable, which is not so beautiful (I think)
```yaml
reverse_proxy:
locations:
frontend:
location: /
proxy_pass: "{{ local_url }}"
proxy_set_header: [] # needed to enable the two next
proxy_http_version: 1.1
websocket: true
```
So this patch try to fix this to allow:
```yaml
reverse_proxy:
locations:
frontend:
location: /
proxy_pass: "{{ local_url }}"
proxy_http_version: 1.1
websocket: true
```
> Allow proxy_http_version and websocket whithout proxy_set_header

- molecule/common/playbook_template.yml
- templates/http/default.conf.j2
- templates/nginx.conf.j2
- templates/stream/default.conf.j2
This will fix #226 -- custom blocks such as `if` blocks are not working as intended unless a comment sign is added at the end of each line
> Remove semicolons from custom_options

- defaults/main/template.yml
- molecule/common/playbook_template.yml
- templates/nginx.conf.j2
This PR addresses issue #180 : A new variable key `nginx_main_template.http_custom_includes` is added. The intended behavior described in #180 can be achieved by setting:
```
nginx_main_template:
http_custom_includes:
- "/etc/nginx/sites-enabled/*.conf"
```
> Adding nginx_main_template.http_custom_includes

- templates/http/default.conf.j2
When using the default http template with `web_server`, if `http_demo_conf` is not defined the template interpolation fails.
-   [X] I have read the [CONTRIBUTING](https://github.com/nginxinc/ansible-role-nginx/blob/master/CONTRIBUTING.md) document
-   [X] I have checked that all unit tests pass after adding my changes
> Fix error when http_demo_conf undefined

- molecule/common/playbook_template.yml
- templates/http/default.conf.j2
- templates/stream/default.conf.j2
Add support for the `down` parameter to allow permanently marking upstream servers as unavailable.
> Add support for down parameter for upstreams

- tasks/conf/logrotate.yml
- tasks/main.yml
Flush handlers before running `nginx -T` and setting up logrotate. This should fix `nginx_debug_output` not working correctly on some systems where the `nginx` service isn't started upon installing `nginx`.
> Flush handlers before running `nginx -T` and setting up logrotate

- molecule/common/playbook_source.yml
- tasks/opensource/setup-source.yml
NGINX automatically creates a root HTML site when installing from source
> Remove root HTML tasks from source install

- tasks/opensource/setup-debian.yml
- tasks/unit/setup-debian.yml
Remove the arch descriptor from the Debian/Ubuntu `deb-src` repos. Resolves #245.
> Remove arch descriptor from Debian/Ubuntu src repo

- tasks/prerequisites/setup-selinux.yml
Typo in Allow Rest API ports, which will throw this:
```
fatal: [192.168.56.154]: FAILED! => {
"msg": "The conditional check 'nginx_rest_api_port is defined\"' failed. The error was: template error while templating string: unexpected char u'\"' at 36. String: {% if nginx_rest_api_port is defined\" %} True {% else %} False {% endif %}
The error appears to be in '/home/test/ansible/roles/nginxinc.nginx/tasks/prerequisites/setup-selinux.yml': line 53, column 3, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
- name: \"(Setup: SELinux: Ports) Allow Rest API ports\"
^ here
This one looks easy to fix. It seems that there is a value started
with a quote, and the YAML parser is expecting to see the line ended
with the same kind of quote. …
```
> Typo in Allow Rest API ports

- .github/pull_request_template.md
- CHANGELOG.md
- README.md
- tasks/main.yml
- tasks/opensource/install-oss-bsd.yml
- tasks/opensource/setup-redhat.yml
- tasks/opensource/setup-source.yml
- tasks/plus/delete-license.yml
- tasks/plus/install-plus-linux.yml
- tasks/plus/setup-license.yml
- tasks/prerequisites/setup-debian.yml
Minor changes to improve formatting.
> Improve formatting

- .travis.yml
- CHANGELOG.md
- molecule/default_centos/molecule.yml
- molecule/module_centos/molecule.yml
- molecule/plus_centos/molecule.yml
- molecule/source_centos/molecule.yml
- molecule/stable_push_centos/molecule.yml
- molecule/template_centos/molecule.yml
- molecule/unit_centos/molecule.yml
- tasks/opensource/install-source.yml
Building NGINX from source should now work as expected in CentOS/RHEL 6 systems running Python `2.6` or earlier versions of `2.7`.
> Add proper support for building NGINX from source in CentOS 6

- .travis.yml
- CHANGELOG.md
- defaults/main/main.yml
- handlers/main.yml
- molecule/common/playbooks/plus_converge.yml
- molecule/common/playbooks/plus_prepare.yml
- molecule/plus/molecule.yml
- molecule/plus_alpine/molecule.yml
- molecule/plus_centos/molecule.yml
- templates/http/api.conf.j2
- templates/http/default.conf.j2
- templates/http/status.conf.j2
- templates/nginx.conf.j2
- templates/stream/default.conf.j2
- templates/www/index.html.j2
- vars/main.yml
Add NGINX Plus tests to TravisCI.
-   [ ] I have added Molecule tests that prove my fix is effective or that my feature works
-   [ ] I have checked that all Molecule tests pass after adding my changes
> Add NGINX Plus tests to TravisCI

- CHANGELOG.md
- README.md
- tasks/main.yml
This PR tweaks how the initial platform assertions are made so that even when the platform is not supported, the role will still attempt to install NGINX on your target platform. Resolves #329.
> Do not fail when assert module fails

- CHANGELOG.md
- handlers/main.yml
The `Check NGINX` handler now always outputs an `ok` state instead of `changed` since it's a read-only operation with no traceable changes.
> Tweak handlers

- CHANGELOG.md
- handlers/main.yml
*   Fix an issue where sometimes the role handlers will fail in distros where NGINX is not started upon installation.
> Swap order of handlers

- .travis.yml
- CHANGELOG.md
Add a conditional check to Travis to only run NGINX Plus related tests on internal builds.
> Add a conditional check to Travis for NGINX Plus builds

- CHANGELOG.md
- tasks/main.yml
- tasks/plus/install-alpine.yml
- tasks/plus/install-debian.yml
- tasks/plus/install-freebsd.yml
- tasks/plus/install-plus.yml
- tasks/plus/install-redhat.yml
- tasks/plus/install-suse.yml
- tasks/plus/remove-license.yml
- vars/main.yml
* Fix issue when removing NGINX Plus license on some distributions. Resolves #336. 
* Fix Amazon Linux NGINX Plus install.
* Optimize NGINX Plus install/remove tasks.
-   [ ] I have checked that all Molecule tests pass after adding my changes
> Fix NGINX Plus license removal option

- CHANGELOG.md
- defaults/main/main.yml
- molecule/common/playbooks/module_converge.yml
- tasks/modules/install-modules.yml
You can now use the following format if you want further fine grained control over how you install modules:
```yaml
- name: njs  # Required
state: present  # Optional
version: =1.19.4+0.4.4-1~bionic  # Optional
```
The old method of specifying modules (using a list of names) still works as expected.
> Implement a new syntax to specify modules to be installed

- CHANGELOG.md
- tasks/prerequisites/setup-selinux.yml
Fix issue whereas SELinux state would not be correctly set back to `enforcing` when `nginx_selinux: true`.
> SELinux state should now be correctly set back to `enforcing`

- .github/workflows/molecule.yml
- CHANGELOG.md
The GitHub actions Molecule CI/CD workflow should now correctly avoid running 'plus' related tests on external PRs.
> Update Molecule CI/CD workflow to avoid running `plus` tests on external PRs

- .github/workflows/molecule.yml
- CHANGELOG.md
- README.md
*   Update Ansible base to `2.10.4`, Ansible to `2.10.5`, Molecule to `3.2.2` and Docker Python SDK to `4.4.1`.
*   Update copyright notice.
> Update Python packages and update copyright notice

- .github/dependabot.yml
- .github/workflows/galaxy.yml
- .github/workflows/molecule.yml
- .github/workflows/requirements.txt
- CHANGELOG.md
- README.md
- meta/main.yml
*   Add support for Dependabot.
*   Only run GitHub actions Galaxy CI/CD workflow when a new release is published.
*   Update list of supported platforms.
> Add support for Dependabot

- CHANGELOG.md
- templates/services/nginx.service.override.conf.j2
This PR is intended as the fix for incorrect setup of systemd `Restart` value.
Current handling of the value within [nginx.service.override.conf.j2](https://github.com/nginxinc/ansible-role-nginx/blob/main/templates/services/nginx.service.override.conf.j2):
```
...
{% if nginx_service_restartonfailure is defined %}
Restart=on-failure
{% endif %}
...
```
`nginx_service_restartonfailure` variable is not defined or mentioned in whole repository, but will keep its usage for backward compatibility and possible use of external value.
My proposed change works with `nginx_service_restart` variable that is already prepared in [systemd.yml](https://github.com/nginxinc/ansible-role-nginx/blob/main/defaults/main/systemd.yml) variable file:
```
...
...
```
-   [x] I have read the …
> Incorrect setup of Systemd restart value

- CHANGELOG.md
- handlers/main.yml
Change the command directory when running the NGINX configuration check handler to prevent edge case errors when the handler is run from a directory that the NGINX process' user does not have access to.
> Change NGINX config check handler directory

- CHANGELOG.md
- README.md
- meta/main.yml
- molecule/default/converge.yml
- molecule/default/molecule.yml
- molecule/module/molecule.yml
- molecule/plus/molecule.yml
- molecule/source/molecule.yml
Add Molecule tests for Alpine 3.13, remove Molecule tests for Debian stretch, and update list of supported platforms.
> Tweak Molecule tests to account for the current supported platforms

- CHANGELOG.md
- README.md
- molecule/plus/molecule.yml
- tasks/opensource/install-source.yml
Per title, add Alpine 3.13 to the list of NGINX Plus supported platforms.
> Add Alpine 3.13 to the list of NGINX Plus supported platforms

- .github/release-drafter.yml
- CHANGELOG.md
- CONTRIBUTING.md
- molecule/plus/converge.yml
- tasks/plus/install-debian.yml
- vars/main.yml
*   The NGINX Plus repository has been updated. This might cause some issues when running the role on an instance that already has NGINX Plus installed. **Starting with NGINX Plus R25, you will need to install NGINX Plus using release `0.20.0`. If you are trying to install R23, please use release `0.19.2`. NGINX Plus R24 should work with both release `0.19.2` and `0.20.0`.**
*   The NGINX Plus modsecurity module is no longer supported by this role. Until NGINX Plus R25 is released, you might keep using release `0.19.2` if you wish to install modsecurity.
-   [x] I have added Molecule tests that …
> Update NGINX Plus repository

- CHANGELOG.md
- tasks/opensource/install-source.yml
Change the url used to grep the latest NGINX version when installing from source. This should avoid the source install failing whenever the `stable` release is higher than the latest `mainline`.
> Update the URL used to fetch the latest NGINX source version

- tasks/main.yml
Ignore Ansible lint warning for `ignore_errors` on a specific instance where `ignore_errors` is required to achieve the desired outcome.
> Ignore Ansible lint warning

- defaults/main/main.yml
- tasks/modules/install-modules.yml
This change adds a `nginx_install_epel_release` feature flag which allows `epel-release` to not be installed by this role if so desired.
This feature flag addresses a need where the epel repository config is managed by other means and should not be configured by this role in order to install Nginx or it's modules. The default behavior of the role is unaltered.
-   [x] I have updated any relevant documentation …
> Add 'nginx_install_epel_release' feature flag to disable the installation of epel-release if so desired

- CHANGELOG.md
- defaults/main/main.yml
- tasks/opensource/install-alpine.yml
- tasks/opensource/install-debian.yml
- tasks/opensource/install-redhat.yml
- tasks/opensource/install-suse.yml
- tasks/plus/install-alpine.yml
- tasks/plus/install-debian.yml
- tasks/plus/install-freebsd.yml
- tasks/plus/install-redhat.yml
- tasks/plus/install-suse.yml
This change adds a `nginx_manage_repo` boolean which can be used to disable Nginx repo management by this role.
This feature flag addresses edge-cases where Nginx' repositories are managed by other means and should not be configured by this role in order to install Nginx. The default behavior of the role is unaltered.
Sidenote on Molecule tests, as a test for setting `nginx_manage_repo` to …
> Add 'nginx_manage_repo' feature flag and defaults

- CHANGELOG.md
- README.md
Remove the deprecation warning in the README detailing the advent of the [NGINX Core Ansible collection](https://github.com/nginxinc/ansible-collection-nginx) and the subsequent splitting from this role of the [Ansible NGINX Config role](https://github.com/nginxinc/ansible-role-nginx-config) and the [Ansible NGINX Unit role](https://github.com/nginxinc/ansible-role-nginx-unit).
-   [x] I have updated any relevant …
> Remove deprecation warning for split up NGINX Config/Unit roles

- CHANGELOG.md
- README.md
- meta/main.yml
- molecule/default/molecule.yml
- molecule/module/molecule.yml
- molecule/plus/molecule.yml
- molecule/source/molecule.yml
* Update the README and Ansible metadata matrix of supported distributions for NGINX Plus.
* Update the Molecule tests to include the newly supported distributions and remove distributions that are no longer supported for NGINX Plus.
> Update list of supported platforms for NGINX Plus R25

- CHANGELOG.md
- molecule/common/Dockerfile.j2
- molecule/default/converge.yml
- tasks/prerequisites/install-dependencies.yml
- tasks/prerequisites/setup-selinux.yml
- vars/main.yml
ENHANCEMENTS:
* Change Ansible Lint exceptions from using an ID identifier to a text identifier.
* Move non NGINX specific dependencies from the role into the Molecule Dockerfile.
BUG FIXES:
Always update NGINX dependencies to the latest available version to avoid outdated dependency issues (e.g. outdated CA certificates).
> Always update NGINX dependencies to the latest available version

- CHANGELOG.md
- tasks/keys/setup-keys.yml
- tasks/modules/install-modules.yml
- tasks/opensource/install-source.yml
Remove RHEL/CentOS 6 task specific parameters given those platforms have reached EOL.
> Remove RHEL/CentOS 6 parameters given they have reached EOL

- CHANGELOG.md
- handlers/main.yml
The Check NGINX handler should now be run in the correct directory in BSD systems.
> Run Check NGINX handler in the correct directory in BSD systems

- CHANGELOG.md
- README.md
- molecule/default/converge.yml
- molecule/default/molecule.yml
- molecule/module/molecule.yml
- molecule/source/molecule.yml
- tasks/keys/setup-keys.yml
- tasks/modules/install-modules.yml
- tasks/opensource/install-alpine.yml
- tasks/opensource/install-debian.yml
- vars/main.yml
FEATURES:
Pin repository data when installing NGINX OSS on Alpine and Debian distributions.
ENHANCEMENTS:
Add Alpine Linux 3.15 to list of tested and supported platforms.
> Pin Alpine and Debian OSS repositories

- .github/workflows/molecule.yml
- CHANGELOG.md
- README.md
- meta/main.yml
- molecule/downgrade/converge.yml
- molecule/downgrade/molecule.yml
- molecule/downgrade/prepare.yml
- molecule/downgrade/verify.yml
- tasks/opensource/install-debian.yml
- tasks/opensource/install-redhat.yml
- tasks/plus/install-debian.yml
- tasks/plus/install-redhat.yml
You can now downgrade versions of NGINX and switch from stable to mainline and viceversa. You will need to specify the NGINX branch and version you wish to install when tweaking versions.
> Allow NGINX version downgrades

- CHANGELOG.md
- tasks/amplify/setup-debian.yml
Fix for #486
```
amazon-ebs.nginx-ami: TASK [nginxinc.nginx : Configure logrotate for NGINX] **************************
amazon-ebs.nginx-ami: skipping: [127.0.0.1]
amazon-ebs.nginx-ami:
amazon-ebs.nginx-ami: TASK [nginxinc.nginx : Install NGINX Amplify] **********************************
amazon-ebs.nginx-ami: included: /tmp/packer-provisioner-ansible-local/62068329-15dc-016c-7d8f-8a91cf418710/roles/nginxinc.nginx/tasks/amplify/install-amplify.yml for 127.0.0.1
amazon-ebs.nginx-ami:
amazon-ebs.nginx-ami: TASK [nginxinc.nginx : Configure NGINX Amplify agent repository] ***************
amazon-ebs.nginx-ami: included: /tmp/packer-provisioner-ansible-local/62068329-15dc-016c-7d8f-8a91cf418710/roles/nginxinc.nginx/tasks/amplify/setup-debian.yml for 127.0.0.1
amazon-ebs.nginx-ami: …
```
> Add GPG key to Focal apt repo setup

- CHANGELOG.md
- README.md
- tasks/amplify/install-amplify.yml
- tasks/amplify/setup-debian.yml
- tasks/amplify/setup-redhat.yml
Update NGINX Amplify repositories to use Python 3 when possible.
> Use Python 3 in NGINX Amplify when possible

- CHANGELOG.md
- defaults/main/main.yml
- molecule/common/Dockerfile.j2
- molecule/default/converge.yml
- molecule/default/molecule.yml
- molecule/downgrade/converge.yml
- molecule/downgrade/molecule.yml
- molecule/downgrade/prepare.yml
- molecule/module/converge.yml
- molecule/module/molecule.yml
- molecule/plus/molecule.yml
- molecule/source/converge.yml
- molecule/source/molecule.yml
- molecule/uninstall/molecule.yml
- molecule/uninstall_plus/converge.yml
- molecule/uninstall_plus/molecule.yml
- molecule/upgrade/molecule.yml
- molecule/upgrade/prepare.yml
- tasks/modules/install-modules.yml
- tasks/opensource/install-source.yml
Add Molecule testing infrastructure for RHEL 7/8.
> Add RHEL distro to Molecule tests

- .github/workflows/requirements/requirements_ansible.yml
- CHANGELOG.md
- meta/main.yml
- tasks/config/setup-logrotate.yml
- tasks/opensource/install-alpine.yml
- tasks/opensource/install-bsd.yml
- tasks/opensource/install-source.yml
- tasks/opensource/install-suse.yml
- tasks/plus/install-alpine.yml
- tasks/plus/install-freebsd.yml
- tasks/plus/install-suse.yml
- tasks/prerequisites/install-dependencies.yml
- tasks/prerequisites/setup-selinux.yml
* Rename all modules to use the fully qualified collection name (FQCN) per Ansible guidelines.
* Bump the Ansible `community.general` collection to `4.6.1` and `community.docker` collection to `2.2.1`.
> Rename modules to use Ansible FQCNs

- CHANGELOG.md
- defaults/main/selinux.yml
- molecule/default/converge.yml
- tasks/prerequisites/setup-selinux.yml
- templates/selinux/nginx-plus-module.te.j2
Streamline configuring SELinux (and fix a couple typos introduced in #500).
> Streamline configuring SELinux

- .github/workflows/requirements/requirements_ansible.yml
- CHANGELOG.md
- README.md
- defaults/main/systemd.yml
- templates/services/nginx.service.override.conf.j2
Add `TimeoutStartSec` parameter to Systemd template and bump `community.docker` collection to `2.3.0`.
> Add `TimeoutStartSec` parameter

- .github/workflows/requirements/requirements_ansible.yml
- CHANGELOG.md
- README.md
Bump `community.general` collection to `4.7.0`.
> Bump `community.general` collection

- CHANGELOG.md
- vars/main.yml
Makes sure `gpg-agent` is present on Ubuntu systems before importing the apt keys, as outlined in #507.
> Ensure `gpg-agent` is installed on Ubuntu

- molecule/plus/molecule.yml
- molecule/uninstall_plus/molecule.yml
Remove RHEL 9 tests involving NGINX Plus.
> NGINX Plus does not yet support RHEL 9

- CHANGELOG.md
- README.md
- molecule/default/molecule.yml
- molecule/module/molecule.yml
- molecule/source/molecule.yml
- molecule/uninstall/molecule.yml
Add Alpine Linux 3.16 to the NGINX OSS list of tested and supported platforms (and remove Alpine Linux 3.12).
> Add Alpine Linux 3.16 as a supported platform

- CHANGELOG.md
- README.md
- molecule/plus/molecule.yml
- molecule/uninstall_plus/molecule.yml
* Add Ubuntu jammy (22.04) to the NGINX list of tested and supported platforms.
* Add RHEL 9 to the NGINX list of tested and supported platforms.
* Add Alpine Linux 3.16 to the NGINX list of tested and supported platforms (and remove Alpine Linux 3.12).
> Support the latest NGINX Plus distro updates

- molecule/downgrade/converge.yml
- molecule/downgrade/molecule.yml
- molecule/downgrade/prepare.yml
- molecule/downgrade/verify.yml
- molecule/upgrade/molecule.yml
- molecule/upgrade/prepare.yml
Ubuntu jammy was missing from both the downgrade and upgrade tests due to a lack of NGINX releases to test both scenarios.
> Add Ubuntu jammy to downgrade and upgrade tests

- CHANGELOG.md
- defaults/main/main.yml
- molecule/downgrade/converge.yml
- molecule/downgrade/molecule.yml
- molecule/downgrade/prepare.yml
- molecule/downgrade/verify.yml
- molecule/upgrade/molecule.yml
- molecule/upgrade/prepare.yml
- tasks/opensource/install-alpine.yml
* Re-add Alpine Linux tests to `downgrade` Molecule scenarios.
* The role can now correctly upgrade NGINX to the latest release on Alpine Linux.
> Fix upgrade & downgrade use cases on Alpine Linux

- .github/workflows/requirements/requirements_ansible.yml
- CHANGELOG.md
- README.md
- meta/main.yml
- tasks/plus/setup-license.yml
Check NGINX Plus license is valid before trying to install NGINX Plus.
> Check NGINX Plus license is valid

- .github/workflows/requirements/requirements_ansible.yml
- CHANGELOG.md
- README.md
- molecule/downgrade_plus/prepare.yml
- molecule/plus/prepare.yml
- molecule/uninstall_plus/prepare.yml
- molecule/upgrade_plus/prepare.yml
- tasks/main.yml
- tasks/plus/install-freebsd.yml
Bump the Ansible `community.general` collection to `5.5.0` and `community.docker` collection to `3.0.2`, and address Linter warnings.
> Bump Ansible collections

- .github/CODEOWNERS
- CHANGELOG.md
- README.md
- defaults/main/main.yml
- molecule/default/converge.yml
- molecule/default/molecule.yml
- molecule/default/verify.yml
- molecule/downgrade/converge.yml
- molecule/downgrade/molecule.yml
- molecule/downgrade/verify.yml
- molecule/downgrade_plus/converge.yml
- molecule/downgrade_plus/molecule.yml
- molecule/downgrade_plus/verify.yml
- molecule/module/molecule.yml
- molecule/plus/molecule.yml
- molecule/source/molecule.yml
- molecule/uninstall/molecule.yml
- molecule/uninstall_plus/molecule.yml
- molecule/upgrade/molecule.yml
- molecule/upgrade/prepare.yml
- molecule/upgrade_plus/molecule.yml
- molecule/upgrade_plus/prepare.yml
- tasks/keys/setup-keys.yml
- tasks/modules/install-modules.yml
- tasks/opensource/install-redhat.yml
- tasks/opensource/install-source.yml
- tasks/plus/install-redhat.yml
- vars/main.yml
Add AlmaLinux, Oracle Linux and Rocky Linux to the list of NGINX OSS tested and supported platforms.
> Support NGINX OSS on AlmaLinux, Oracle Linux, and Rocky Linux

- .github/workflows/galaxy.yml
- .github/workflows/molecule.yml
- .github/workflows/release-drafter.yml
- CHANGELOG.md
- molecule/common/Dockerfile.j2
- molecule/default/molecule.yml
- molecule/downgrade/molecule.yml
- molecule/downgrade_plus/molecule.yml
- molecule/module/molecule.yml
- molecule/plus/molecule.yml
- molecule/source/molecule.yml
- molecule/uninstall/molecule.yml
- molecule/uninstall_plus/molecule.yml
- molecule/upgrade/molecule.yml
- molecule/upgrade_plus/molecule.yml
Update GitHub actions to run on Ubuntu 22.04 and to only skip ~plus~ scenarios when the NGINX Plus license secrets are not present (it used to only run the scenarios during internal PRs).
> Update GitHub actions to use Ubuntu 22.04

- .github/workflows/molecule.yml
- CHANGELOG.md
GitHub actions should now correctly skip \*plus\* scenarios only when the NGINX Plus license secrets are not present.
> Fix tests not running on external PRs

- CHANGELOG.md
- molecule/default/molecule.yml
- molecule/downgrade/molecule.yml
- molecule/downgrade_plus/molecule.yml
- molecule/module/molecule.yml
- molecule/plus/molecule.yml
- molecule/source/molecule.yml
- molecule/uninstall/molecule.yml
- molecule/uninstall_plus/molecule.yml
- molecule/upgrade/molecule.yml
- molecule/upgrade_plus/molecule.yml
Explicitly specify `amd64` as the platform used in Molecule tests. This will ensure that tests work as expected when run on different host architectures (e.g. newer Macbooks with `arm` processors).
> Use `amd64` platform for Molecule tests

- CHANGELOG.md
- defaults/main/main.yml
- molecule/source/converge.yml
- tasks/opensource/install-source.yml
- vars/main.yml
BREAKING CHANGES:
* When building from source the various libraries required to build NGINX from source, you will no longer need to specify the name of the package, only the version:
```yaml
pcre_version: pcre2-10.42
```
is now:
```yaml
pcre_version: 10.42
```
* The `nginx_install_source_<package>: false` parameters have been reversed. Setting `nginx_install_source_pcre: true` will now build PCRE from source, instead of using the default package manager. The previous behavior was unintuitive at best.
ENHANCEMENTS:
Use the official GitHub repositories as the source for the various packages required to compile NGINX OSS from source.
BUG FIXES:
Update the versions of the various packages required to build NGINX from source. The version of `zlib` listed in the role was no longer available. …
> Improve workflow for building NGINX from source

- CHANGELOG.md
- molecule/default/molecule.yml
- molecule/downgrade/molecule.yml
- molecule/downgrade_plus/molecule.yml
- molecule/module/molecule.yml
- molecule/plus/molecule.yml
- molecule/source/molecule.yml
- molecule/uninstall/molecule.yml
- molecule/uninstall_plus/molecule.yml
- molecule/upgrade/molecule.yml
- molecule/upgrade_plus/molecule.yml
**Note:** This PR partially reverts the changes made in #572.
Explicitly specify `amd64` as the platform used in the Amazon Linux 2/CentOS/Oracle Linux/RHEL 7/SLES 15 Molecule Docker images. This will ensure that tests work when run on different host architectures (e.g. newer Macbooks with `arm64` processors) when running tests in distributions that only support `amd64` (either due to lack of support for a `cgroups` v2 backport or due to lack of builds for `arm64`).
> Update Molecule platform data

- .github/CODEOWNERS
- .github/workflows/galaxy.yml
- .github/workflows/molecule.yml
- .github/workflows/release-drafter.yml
- CHANGELOG.md
- README.md
The `ignore-tags` GitHub actions key does not exist. Replace it with the correct key, `tags-ignore`.
> Replace non-existent GitHub actions key

- .github/workflows/molecule.yml
- CHANGELOG.md
- README.md
- defaults/main/main.yml
- molecule/distribution/converge.yml
- molecule/distribution/molecule.yml
- molecule/distribution/verify.yml
- tasks/opensource/install-distribution.yml
- tasks/opensource/install-oss.yml
BUG FIXES:
Fix the NGINX installation process when installing NGINX from a distribution's package repository in CentOS/RHEL 7 based distributions.
TESTS:
Add `distribution` Molecule scenario.
> Add `distribution` Molecule scenario

- CHANGELOG.md
- molecule/default/verify.yml
- tasks/prerequisites/prerequisites.yml
We installed Oracle Linux on our VMWare Cluster. We noticed the SELinux configuration is like any other rhel OS so would like to enable ability to configure this by setting the nginx_selinux variable in this role.
> Enable SELinux config with Oracle Linux

- .github/workflows/molecule.yml
- .github/workflows/requirements/requirements_ansible_lint.txt
- CHANGELOG.md
- molecule/default/molecule.yml
- molecule/distribution/molecule.yml
- molecule/downgrade-plus/molecule.yml
- molecule/downgrade/molecule.yml
- molecule/plus/molecule.yml
- molecule/source/molecule.yml
- molecule/stable/molecule.yml
- molecule/uninstall-plus/molecule.yml
- molecule/uninstall/molecule.yml
- molecule/upgrade-plus/molecule.yml
- molecule/upgrade/molecule.yml
- molecule/version/molecule.yml
Split Ansible Lint into its own GH actions job since Molecule no longer runs linters natively.
> Extract Ansible Lint into its own GH actions job

- CHANGELOG.md
- tasks/plus/setup-license.yml
NGINX Plus was failing to install on OracleLinux 8 due to a mismatch in python3 versions for the cryptography package
> fix: OracleLinux 8 uses python3.11 cryptography

- .ansible-lint
- .github/workflows/molecule.yml
- .github/workflows/requirements/requirements_ansible.yml
- .github/workflows/requirements/requirements_ansible_lint.txt
- .github/workflows/requirements/requirements_molecule.txt
- CHANGELOG.md
- README.md
- meta/main.yml
- molecule/default/molecule.yml
- molecule/default/verify.yml
- molecule/distribution/molecule.yml
- molecule/downgrade-plus/molecule.yml
- molecule/downgrade/molecule.yml
- molecule/plus/molecule.yml
- molecule/source/molecule.yml
- molecule/stable/molecule.yml
- molecule/uninstall-plus/molecule.yml
- molecule/uninstall/molecule.yml
- molecule/upgrade-plus/molecule.yml
- molecule/upgrade/molecule.yml
- molecule/version/converge.yml
- molecule/version/molecule.yml
- molecule/version/verify.yml
- tasks/validate/validate.yml
- vars/main.yml
This "small" PR ended up becoming way bigger than initially intended by virtue of multiple issues arising with the GitHub Actions pipeline. As a result, some tests have been temporarily taken out until a fix for the pipeline is found. It should be noted all tests pass correctly as expected when ran locally, so the issue with the pipeline should indicate there being an issue with the codebase.
FEATURES:
- Add Alpine Linux 3.18, Debian bookworm, and Ubuntu kinetic/lunar to the list of NGINX OSS tested and supported distributions.
- Remove Alpine Linux 3.14 from the list of NGINX OSS tested and supported distributions.
ENHANCEMENTS:
Bump the Ansible `ansible.posix` collection to `1.5.4`, `community.general` collection to `6.4.0`, `community.crypto` collection to `2.14.1` and …
> Update 1.25.1 supported distributions

- .github/workflows/molecule.yml
- CHANGELOG.md
- README.md
- molecule/downgrade-plus/converge.yml
- molecule/downgrade-plus/molecule.yml
- molecule/downgrade-plus/verify.yml
- molecule/plus/molecule.yml
- molecule/plus/verify.yml
- molecule/uninstall-plus/molecule.yml
- molecule/upgrade-plus/molecule.yml
- molecule/upgrade-plus/prepare.yml
- molecule/upgrade-plus/verify.yml
- tasks/modules/install-modules.yml
- vars/main.yml
- Add Alpine Linux 3.18 and Debian bookworm to the list of NGINX Plus tested and supported distributions.
- Remove Alpine Linux 3.14 and Ubuntu bionic from the list of NGINX Plus tested and supported distributions.
> Support NGINX Plus R30

- .github/workflows/molecule.yml
- CHANGELOG.md
- README.md
- molecule/default/verify.yml
- molecule/downgrade-plus/converge.yml
- molecule/downgrade-plus/molecule.yml
- molecule/downgrade-plus/verify.yml
- molecule/downgrade/converge.yml
- molecule/downgrade/molecule.yml
- molecule/downgrade/verify.yml
- molecule/plus/molecule.yml
- molecule/plus/verify.yml
- molecule/stable/verify.yml
- molecule/uninstall-plus/molecule.yml
- molecule/upgrade-plus/molecule.yml
- molecule/upgrade-plus/prepare.yml
- molecule/upgrade-plus/verify.yml
- molecule/upgrade/molecule.yml
- molecule/upgrade/prepare.yml
- molecule/upgrade/verify.yml
- molecule/version/verify.yml
- tasks/modules/install-modules.yml
- vars/main.yml
- Reimplement some platforms in the upgrade & downgrade Molecule scenarios since all platforms now have at least two releases.
- Replace the hardcoded NGINX version check in multiple Molecule scenarios with a dynamic NGINX version check.
> Update Molecule CI/CD to support NGINX 1.25.2

- CHANGELOG.md
- README.md
- meta/main.yml
- molecule/default/molecule.yml
- molecule/downgrade/molecule.yml
- molecule/source/molecule.yml
- molecule/stable/molecule.yml
- molecule/uninstall/molecule.yml
- molecule/upgrade/molecule.yml
- molecule/version/molecule.yml
Remove Ubuntu kinetic from the list of NGINX OSS tested and supported distributions.
> Remove Ubuntu kinetic

- .github/workflows/molecule.yml
- CHANGELOG.md
- README.md
- molecule/amplify/cleanup.yml
- molecule/amplify/converge.yml
- molecule/amplify/molecule.yml
- molecule/amplify/verify.yml
- tasks/amplify/install-amplify.yml
- tasks/amplify/setup-debian.yml
- tasks/main.yml
And add Molecule tests for NGINX Amplify. Fixes #667.
> Avoid re-copying the NGINX Amplify config file every time the role is re-run

- CHANGELOG.md
- README.md
- meta/main.yml
- molecule/downgrade-plus/converge.yml
- molecule/downgrade-plus/molecule.yml
- molecule/downgrade-plus/verify.yml
- molecule/plus/molecule.yml
- molecule/uninstall-plus/molecule.yml
- molecule/upgrade-plus/molecule.yml
- molecule/upgrade-plus/prepare.yml
- vars/main.yml
- Add Alpine Linux 3.19 to the list of NGINX Plus tested and supported distributions.
- Remove Alpine Linux 3.15 from the list of NGINX Plus tested and supported distributions.
> Update Molecule to support NGINX Plus R31

- CHANGELOG.md
- molecule/default/converge.yml
- molecule/distribution/converge.yml
- molecule/downgrade-plus/converge.yml
- molecule/downgrade/converge.yml
- molecule/plus/converge.yml
- molecule/source-version/converge.yml
- molecule/source/converge.yml
- molecule/stable/converge.yml
- molecule/uninstall-plus/converge.yml
- molecule/uninstall/converge.yml
- molecule/upgrade-plus/converge.yml
- molecule/upgrade/converge.yml
- molecule/version/converge.yml
Use the local role name (ansible-role-nginx) instead of the fully qualified role name (nginxinc.nginx) in Molecule to ensure tests always work as intended in environments where the role has been already installed beforehand.
> Use local role name in Molecule tests

- CHANGELOG.md
- tasks/validate/validate.yml
When ansible-core version is updated from 2.15.4 to 2.15.8 the following warning occurs:
[WARNING]: conditional statements should not include jinja2 templating delimiters such as {{ }} or {% %}
Fixed by removing the delimeters.
Describe the use case and detail of the change. If this PR addresses an issue on GitHub, make sure to include a link to that issue using one of the [supported keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) here in this description (not in the title of the PR).
> fix: conditional statements jinja2 warning

- .github/workflows/f5-cla.yml
Adds a GitHub actions workflow configured for F5 contributor license agreement automation and compliance. This action is configured to target a shared signature store for F5 Open Source projects. As part of the configuration, the following GitHub usernames were whitelisted as maintainers:
* `oxpa`
* `alessfg`
Any contributors not included in this whitelist will be asked to review the [F5 CLA](https://github.com/f5/.github/blob/main/CLA/cla-markdown.md), upon a pull request, and post a comment agreeing to the terms before their contribution is merged.  
> ci: add gh action workflow for F5 CLA automation

- CHANGELOG.md
- tasks/opensource/install-bsd.yml
Fix issue when installing NGINX on BSD systems. Fixes #711.
> Fix installing NGINX on BSD systems

- CHANGELOG.md
- README.md
- molecule/default/molecule.yml
- molecule/distribution/molecule.yml
- molecule/downgrade-plus/converge.yml
- molecule/downgrade-plus/molecule.yml
- molecule/downgrade/converge.yml
- molecule/downgrade/molecule.yml
- molecule/plus/molecule.yml
- molecule/source-version/molecule.yml
- molecule/source/molecule.yml
- molecule/stable/molecule.yml
- molecule/uninstall-plus/molecule.yml
- molecule/uninstall/molecule.yml
- molecule/upgrade-plus/molecule.yml
- molecule/upgrade-plus/prepare.yml
- molecule/upgrade/molecule.yml
- molecule/upgrade/prepare.yml
- molecule/version/converge.yml
- molecule/version/molecule.yml
- tasks/keys/setup-keys.yml
- vars/main.yml
- Add Ubuntu noble (24.04) to the list of NGINX OSS and NGINX Plus tested and supported distributions.
- Add Ubuntu matic (23.10) to the list of supported NGINX OSS distributions.
- Remove Ubuntu lunar (23.04) from the list of supported NGINX OSS distributions.
> Update list of supported NGINX versions

- .github/workflows/requirements/requirements_molecule.txt
- CHANGELOG.md
Hardcode version of Python requests module given its propensity to break the Docker Python SDK.
> Hardcode version of requests Python module

- .github/workflows/molecule.yml
- CHANGELOG.md
- molecule/agent/molecule.yml
- molecule/amplify/molecule.yml
- molecule/default/molecule.yml
- molecule/distribution/molecule.yml
- molecule/downgrade-plus/molecule.yml
- molecule/downgrade/molecule.yml
- molecule/plus/molecule.yml
- molecule/source-version/molecule.yml
- molecule/source/molecule.yml
- molecule/stable/molecule.yml
- molecule/uninstall-plus/molecule.yml
- molecule/uninstall/molecule.yml
- molecule/upgrade-plus/molecule.yml
- molecule/upgrade/molecule.yml
- molecule/version/molecule.yml
Remove commented out Molecule platforms and GitHub Actions QEMU step for the time being. These changes will be reverted if multi-arch testing can be reinstated in GitHub Actions.
> chore: Remove commented out Molecule platforms

- .ansible-lint
- CHANGELOG.md
- meta/main.yml
Remove platform metadata from the Ansible Galaxy role metadata since platforms are no longer supported in Ansible Galaxy NG.
> chore: Remove platform metadata from the Ansible Galaxy role metadata

- .github/workflows/f5-cla.yml
- .github/workflows/release.yml
- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- tasks/validate/validate.yml
- vars/main.yml
Use a variable to set the minimum version of Ansible and Jinja2 allowed.
> feat: Improve Ansible/Jinja2 validation

- CHANGELOG.md
- tasks/opensource/install-debian.yml
- tasks/opensource/install-redhat.yml
- tasks/plus/install-debian.yml
- tasks/plus/install-redhat.yml
No longer omit `allow_downgrade` module parameter when running Ansible versions lower than `2.12`.
> chore!: Do not omit `allow_downgrade` module parameter on Ansible <2.12

- CHANGELOG.md
- tasks/modules/install-modules.yml
Installing certain NGINX modules on Alpine Linux 3.17 no longer requires installing `nginx-plus-module-ndk` as a separate step. This PR also includes a minor bug fix hat should have been part of the original PR removing support for RHEL 7 based distributions involving EPEL 7 repos being no longer available.
> chore: Remove unnecessary task when installing modules on Alpine Linux

- CHANGELOG.md
- defaults/main/agent.yml
- handlers/main.yml
- molecule/agent/converge.yml
- tasks/agent/install-agent.yml
- templates/nginx-agent/agent-dynamic.conf.j2
- templates/nginx-agent/nginx-agent.conf.j2
Add support for templating the entire NGINX Agent configuration file.
> feat: Add NGINX Agent config template

- CHANGELOG.md
- molecule/version/converge.yml
- tasks/modules/install-modules.yml
Correctly use the `nginx_version` (if defined) for NGINX module versions. Fixes #861.
> fix: Use `nginx_version` when installing NGINX modules

- CHANGELOG.md
- defaults/main/main.yml
- molecule/distribution/converge.yml
- molecule/distribution/verify.yml
- tasks/opensource/install-distribution.yml
Add a parameter, `nginx_distribution_package`, to override the default NGINX package name when installing NGINX from your distribution/OS repository. Supersedes #857.
> feat: Allow overriding distribution package name

- CHANGELOG.md
- README.md
- molecule/agent/cleanup.yml
- molecule/agent/converge.yml
- molecule/agent/molecule.yml
- molecule/agent/verify.yml
- molecule/default/molecule.yml
- molecule/distribution/molecule.yml
- molecule/downgrade-plus/molecule.yml
- molecule/downgrade/converge.yml
- molecule/downgrade/molecule.yml
- molecule/plus/converge.yml
- molecule/plus/molecule.yml
- molecule/source-version/molecule.yml
- molecule/source/molecule.yml
- molecule/stable/molecule.yml
- molecule/uninstall-plus/molecule.yml
- molecule/uninstall/molecule.yml
- molecule/upgrade-plus/molecule.yml
- molecule/upgrade/molecule.yml
- molecule/upgrade/prepare.yml
- molecule/version/converge.yml
- molecule/version/molecule.yml
- tasks/agent/install-agent.yml
- tasks/modules/install-modules.yml
- vars/main.yml
Add support for installing NGINX Open Source and NGINX Plus on Alpine Linux 3.21 and remove support for installing NGINX Plus on Alpine Linux 3.17. 
> feat!: Remove Alpine 3.17 and add Alpine 3.21

- CHANGELOG.md
- defaults/main/main.yml
- handlers/main.yml
Add a parameter, `nginx_skip_os_install_config_check`, to turn off the NGINX config check handler when installing NGINX from the respective distribution package manager. This should help avoid potential issues where the default NGINX config that ships with a distribution is broken for some reason. Resolves #888
> feat: Allow skipping config check when installing NGINX from an OS repo
